name: "Release"
on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0


            -   name: set up npm
                uses: actions/setup-node@v4
                with:
                    node-version: '21'
                    cache: 'yarn'

            -   name: set up go
                uses: actions/setup-go@v5
                with:
                    go-version: '^1.22.7'
            #            - name: "📔 Generate a changelog"
            #              uses: orhun/git-cliff-action@v3
            #              with:
            #                  config: cliff.toml
            #                  args: --verbose --latest
            #              env:
            #                  OUTPUT: CHANGELOG_temp.md

            -   name: Build plugin
                run: |
                    yarn
                    yarn run build
                    go build -o pty-server main.go

            -   name: Get the tag
                id: get_tag
                run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}


            -   name: Create release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                         tag=${{ steps.get_tag.outputs.tag }}
                         
                         gh release create "$tag" \
                         --title="$tag" \
                         --draft \
                  #                  --notes-file=CHANGELOG_temp.md \
                         main.js manifest.json styles.css  README.md pty-server
